# Generated by Django 5.2 on 2025-05-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submitted_video',
            field=models.FileField(blank=True, null=True, upload_to='submissions/videos/'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submitted_zip',
            field=models.FileField(blank=True, null=True, upload_to='submissions/zips/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='possible_grades',
            field=models.IntegerField(),
        ),
    ]
