# Generated by Django 5.2 on 2025-05-08 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_assignmentsubmission_submitted_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='faculty_name',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='faculty_name',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student_name',
            field=models.CharField(default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
