# Generated by Django 5.2 on 2025-05-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_assignmentsubmission_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
